These tests...
os::canonicalize_ok_if_relative_path
os::canonicalize_ok_if_path_ends_in_dotdot

...both do something like this:

A = current working directory
B = A - with redirection appended
assert(canonicalize(B) == A)

What if A is not already canonical?  I think the place Mac OS puts its temp directories has a symlink in the path, and that's why these tests fail on mac.  I propose fixing by adding an extra call to canonicalize in the check, so it looks more like this:

A = current working directory
B = A - with trivial redirection
assert(canonicalize(B) == canonicalize(A))

These tests:

os::canonicalize_ok_with_dotdot_if_paths_exist
os::canonicalize_ok_if_file_exists

have the same issue as above, but the fix is slightly different.  Here, I'm adding an extra check that reads the file contents at the canonicalized path, the idea is that guard against canonicalize returning the same wrong answer in both places.

This test:

os::remove_file_fails_if_node_is_a_directory

I think what's happening here is: when you remove_file a directory on Mac, it gives a different error-type from other OS's.  Mac gives you a permissions error (this seems wrong to me, but that's what it does)  If I run this...

use std::fs;

fn main() -> std::io::Result<()> {
    fs::create_dir("stuff")?;
    fs::remove_file("stuff")?;
    Ok(())
}

on rust-playground, I get:

Error: Os { code: 21, kind: Other, message: "Is a directory" }

On my Mac, I get:

Error: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }

This test:

os::canonicalize_fails_if_subpath_is_file

I'm pretty sure is failing because the underlying fs call doesn't do the right thing.  I can verify by running this code:

use std::fs;
use std::io::prelude::*;

fn main() -> std::io::Result<()> {
    fs::create_dir("stuff")?;
    let mut f = fs::File::create("stuff/thing")?;
    f.write_all(b"content")?;
    let path = fs::canonicalize("stuff/thing/../thing")?;
    println!("My new path {}", path.to_str().unwrap());
    Ok(())
}

If I run that on the rust playground, I get an error.  If I run it on my mac, I get no error and it prints:

My new path /Users/ptrethewey/source/fileexper/stuff/thing

Rust documentation (https://doc.rust-lang.org/std/fs/fn.canonicalize.html) says the function should error if "a non-final component in path is not a directory"

So, the fix I propose is to modify os::canonicalize so that it does what the rust docs say, by adding an explicit check that each partial path is a directory, and manufacture the right error.